---
- name: Deploy resources via OpenTofu
  hosts: localhost
  tasks:
    - name: Destroy EC2 instance using OpenTofu
      cloud.terraform.terraform:
        project_path: ../opentofu/
        state: absent
        force_init: true
        backend_config_files:
          - "{{ lookup('ansible.builtin.env', 'TF_BACKEND_CONFIG_FILE') }}" # Note use of the env variable set by the OpenTofu backend credential to store the backend configuration file path
      register: output

    - debug:
        var: output['stdout_lines']
